import {
    NavigationContainer,
    DarkTheme as NavigationDarkTheme,
    DefaultTheme as NavigationDefaultTheme,
} from "@react-navigation/native";
import {
    DarkTheme as PaperDarkTheme,
    DefaultTheme as PaperDefaultTheme,
    Provider as PaperProvider,
} from "react-native-paper";

export const CombinedDefaultThemes = [{
    ...PaperDefaultTheme,
    ...NavigationDefaultTheme,
    colors: {
        ...PaperDefaultTheme.colors,
        ...NavigationDefaultTheme.colors,
        primary: "#BB1822",
        onPrimary: "#FFFFFF",
        primaryContainer: "#FFDAD5",
        onPrimaryContainer: "#410003",
        secondary: "#C00103",
        onSecondary: '#FFFFFF',
        secondaryContainer: '#FFDAD3',
        onSecondaryContainer: '#410000',
        tertiary: '#725B2E',
        onTertiary: '#FFFFFF',
        tertiaryContainer: '#FFDEA6',
        onTertiaryContainer: '#271900',
        error: '#BA1B1B',
        onError: '#FFFFFF',
        errorContainer: '#FFDAD4',
        onErrorContainer: '#410001',
        background: '#FBFDFD',
        onBackground: '#191C1D',
        surface: '#FBFDFD',
        onSurface: '#191C1D',
        surfaceVariant: '#F4DDDB',
        onSurfaceVariant: '#524342',
        outline: '#857371',
        surface1: '#F8F2F2',
        surface2: '#F6EBEB',
        surface3: '#F4E4E5',
        surface4: '#F3E2E3',
        surface5: '#F2DDDE',
        headerActive: '#F2DDDE',
        headerInactive: '#F8F2F2',
        onHeaderInactive: "#191C1D",
        onHeader: '#191C1D',
    }
},
{
    ...PaperDefaultTheme,
    ...NavigationDefaultTheme,
    "colors": {
        ...PaperDefaultTheme.colors,
        ...NavigationDefaultTheme.colors,
        "background": "#FCFCFC",
        "black": "#000000",
        "error": "#BA1B1B",
        "errorContainer": "#FFDAD4",
        "headerActive": "#E92F2F",
        "headerInactive": "#F1F1F1",
        "onHeaderInactive": "#000000",
        "inverseOnSurface": "#FBEEEC",
        "inversePrimary": "#FFB3A9",
        "inverseSurface": "#362F2E",
        "onBackground": "#211A19",
        "onError": "#FFFFFF",
        "onErrorContainer": "#410001",
        "onHeader": "#000000",
        "onPrimary": "#FFFFFF",
        "onPrimaryContainer": "#410002",
        "onSecondary": "#FFFFFF",
        "onSecondaryContainer": "#B72A2A",
        "onSurface": "#211A19",
        "onSurfaceVariant": "#534341",
        "onTertiary": "#FFFFFF",
        "onTertiaryContainer": "#261900",
        "outline": "#857371",
        "primary": "#E92F2F",
        "primaryContainer": "#FFDAD4",
        "secondary": "#775653",
        "secondaryContainer": "#FFDAD5",
        "shadow": "#000000",
        "surface": "#FCFCFC",
        "surface1": "#F1F1F1",
        "surface2": "#F2F2F2",
        "surface3": "#FAFCFD",
        "surface4": "#FCFCFC",
        "surface5": "#EAE3F1",
        "surfaceVariant": "#DBE4E6",
        "tertiary": "#715B2E",
        "tertiaryContainer": "#FEDFA6",
        "white": "#FFFFFF",
    }
},{
    ...PaperDefaultTheme,
    ...NavigationDefaultTheme,
    "colors": {
        ...PaperDefaultTheme.colors,
        ...NavigationDefaultTheme.colors,
        "background": "#FCFCFC",
        "black": "#000000",
        "error": "#BA1B1B",
        "errorContainer": "#FFDAD4",
        "headerActive": "#E9E3EE",
        "headerInactive": "#F5F3F7",
        "onHeaderInactive": "#000000",
        "inverseOnSurface": "#F6EFF4",
        "inversePrimary": "#E3B6FF",
        "inverseSurface": "#322F33",
        "onBackground": "#1D1B1E",
        "onError": "#FFFFFF",
        "onErrorContainer": "#410001",
        "onHeader": "#000000",
        "onPrimary": "#FFFFFF",
        "onPrimaryContainer": "#2E004F",
        "onSecondary": "#FFFFFF",
        "onSecondaryContainer": "#221729",
        "onSurface": "#1D1B1E",
        "onSurfaceVariant": "#4B454D",
        "onTertiary": "#FFFFFF",
        "onTertiaryContainer": "#331015",
        "outline": "#7C757E",
        "primary": "#774A9B",
        "primaryContainer": "#F4DAFF",
        "secondary": "#675A6F",
        "secondaryContainer": "#EEDDF5",
        "shadow": "#000000",
        "surface": "#FCFCFC",
        "surface1": "#F5F3F7",
        "surface2": "#F1EEF4",
        "surface3": "#EDE8F1",
        "surface4": "#ECE7F0",
        "surface5": "#E9E3EE",
        "surfaceVariant": "#EADFEA",
        "tertiary": "#815155",
        "tertiaryContainer": "#FFD9DC",
        "white": "#FFFFFF"
    }
},
{
    ...PaperDefaultTheme,
    ...NavigationDefaultTheme,
    "colors": {
        ...PaperDefaultTheme.colors,
        ...NavigationDefaultTheme.colors,
        "background": "#FCFCFC",
        "black": "#000000",
        "error": "#BA1B1B",
        "errorContainer": "#FFDAD4",
        "headerActive": "#EFE1E6",
        "headerInactive": "#F7F2F4",
        "inverseOnSurface": "#FAEEEF",
        "inversePrimary": "#FFB1C7",
        "inverseSurface": "#352F30",
        "onBackground": "#201A1B",
        "onError": "#FFFFFF",
        "onErrorContainer": "#410001",
        "onHeader": "#000",
        "onHeaderInactive": "#000",
        "onPrimary": "#FFFFFF",
        "onPrimaryContainer": "#3F001A",
        "onSecondary": "#FFFFFF",
        "onSecondaryContainer": "#2B151B",
        "onSurface": "#201A1B",
        "onSurfaceVariant": "#514346",
        "onTertiary": "#FFFFFF",
        "onTertiaryContainer": "#2D1600",
        "outline": "#837376",
        "primary": "#A1385D",
        "primaryContainer": "#FFD9E2",
        "secondary": "#74565D",
        "secondaryContainer": "#FFD9E1",
        "shadow": "#000000",
        "surface": "#FCFCFC",
        "surface1": "#F7F2F4",
        "surface2": "#F5ECEF",
        "surface3": "#F2E6EB",
        "surface4": "#F1E4E9",
        "surface5": "#EFE1E6",
        "surfaceVariant": "#F3DDE1",
        "tertiary": "#7C5734",
        "tertiaryContainer": "#FFDCBD",
        "white": "#FFFFFF"
    }
}

];

export const CombinedDarkThemes = [{
    ...PaperDarkTheme,
    ...NavigationDarkTheme,
    colors: {
        ...PaperDarkTheme.colors,
        ...NavigationDarkTheme.colors,
        primary: '#FFB3AB',
        onPrimary: '#680008',
        primaryContainer: '#930010',
        onPrimaryContainer: '#FFDAD5',
        secondary: '#FFB4A7',
        onSecondary: '#680000',
        secondaryContainer: '#930000',
        onSecondaryContainer: '#FFDAD3',
        tertiary: '#E1C28C',
        onTertiary: '#402D05',
        tertiaryContainer: '#584319',
        onTertiaryContainer: '#FFDEA6',
        error: '#FFB4A9',
        onError: '#680003',
        errorContainer: '#930006',
        onErrorContainer: '#FFDAD4',
        background: '#191C1D',
        onBackground: '#E0E3E3',
        surface: '#191C1D',
        onSurface: '#E0E3E3',
        surfaceVariant: '#524342',
        onSurfaceVariant: '#D7C1BF',
        outline: '#A08C8A',
        surface1: '#242424',
        surface2: '#2B2828',
        surface3: '#322D2D',
        surface4: '#352E2E',
        surface5: '#393131',
        headerActive: '#393131',
        headerInactive: '#242424',
        onHeader: '#E0E3E3',
        onHeaderInactive: '#E0E3E3',
    },
},
{
    ...PaperDarkTheme,
    ...NavigationDarkTheme,
    colors: {
        ...PaperDarkTheme.colors,
        ...NavigationDarkTheme.colors,
        "background": "#211A19",
        "black": "#000000",
        "error": "#FFB4A9",
        "errorContainer": "#930006",
        "headerActive": "#E92F2F",
        "headerInactive": "#1C2527",
        "onHeaderInactive": "#FFFFFF",
        "inverseOnSurface": "#211A19",
        "inversePrimary": "#C00417",
        "inverseSurface": "#EDE0DE",
        "onBackground": "#EDE0DE",
        "onError": "#680003",
        "onErrorContainer": "#FFDAD4",
        "onHeader": "#FFFFFF",
        "onPrimary": "#FFFFFF",
        "onPrimaryContainer": "#95F0FF",
        "onSecondary": "#001F24",
        "onSecondaryContainer": "#FFDAD6",
        "onSurface": "#EDE0DE",
        "onSurfaceVariant": "#D8C2BF",
        "onTertiary": "#3F2D04",
        "onTertiaryContainer": "#FEDFA6",
        "outline": "#899294",
        "primary": "#E92F2F",
        "primaryContainer": "#93000A",
        "secondary": "#E7BDB8",
        "secondaryContainer": "#93000F",
        "shadow": "#000000",
        "surface": "#191C1D",
        "surface1": "#1C2527",
        "surface2": "#191C1D",
        "surface3": "#FFFFFF",
        "surface4": "#211A19",
        "surface5": "#211A19",
        "surfaceVariant": "#534341",
        "tertiary": "#E1C38C",
        "tertiaryContainer": "#584419",
        "white": "#FFFFFF"
    }
},{

    ...PaperDarkTheme,
    ...NavigationDarkTheme,
    colors: {
        ...PaperDarkTheme.colors,
        ...NavigationDarkTheme.colors,
        "background": "#1D1B1E",
        "black": "#000000",
        "error": "#FFB4A9",
        "errorContainer": "#930006",
        "headerActive": "#39313D",
        "headerInactive": "#272329",
        "onHeaderInactive": "#FFFFFF",
        "onHeader": "#ffffff",
        "inverseOnSurface": "#1D1B1E",
        "inversePrimary": "#774A9B",
        "inverseSurface": "#E7E0E5",
        "onBackground": "#E7E0E5",
        "onError": "#680003",
        "onErrorContainer": "#FFDAD4",
        "onPrimary": "#461968",
        "onPrimaryContainer": "#F4DAFF",
        "onSecondary": "#372C3E",
        "onSecondaryContainer": "#EEDDF5",
        "onSurface": "#E7E0E5",
        "onSurfaceVariant": "#CDC4CE",
        "onTertiary": "#4C2529",
        "onTertiaryContainer": "#FFD9DC",
        "outline": "#968E98",
        "primary": "#E3B6FF",
        "primaryContainer": "#5E3280",
        "secondary": "#D2C1D9",
        "secondaryContainer": "#4E4256",
        "shadow": "#000000",
        "surface": "#1D1B1E",
        "surface1": "#272329",
        "surface2": "#2D2730",
        "surface3": "#332C37",
        "surface4": "#352E39",
        "surface5": "#39313D",
        "surfaceVariant": "#4B454D",
        "tertiary": "#F4B7BB",
        "tertiaryContainer": "#663A3E",
        "white": "#FFFFFF"
    }
},
{
    ...PaperDarkTheme,
    ...NavigationDarkTheme,
    colors: {
        ...PaperDarkTheme.colors,
        ...NavigationDarkTheme.colors,
        "background": "#201A1B",
        "black": "#000000",
        "error": "#FFB4A9",
        "errorContainer": "#930006",
        "headerActive": "#3F2F33",
        "headerInactive": "#2B2224",
        "onHeaderInactive": "#FFFFFF",
        "inverseOnSurface": "#201A1B",
        "inversePrimary": "#A1385D",
        "inverseSurface": "#EBE0E1",
        "onBackground": "#EBE0E1",
        "onError": "#680003",
        "onErrorContainer": "#FFDAD4",
        "onHeader": "#ffffff",
        "onPrimary": "#640430",
        "onPrimaryContainer": "#FFD9E2",
        "onSecondary": "#432930",
        "onSecondaryContainer": "#FFD9E1",
        "onSurface": "#EBE0E1",
        "onSurfaceVariant": "#D6C1C5",
        "onTertiary": "#472A0B",
        "onTertiaryContainer": "#FFDCBD",
        "outline": "#9E8D90",
        "primary": "#FFB1C7",
        "primaryContainer": "#832046",
        "secondary": "#E3BDC5",
        "secondaryContainer": "#5B3F46",
        "shadow": "#000000",
        "surface": "#201A1B",
        "surface1": "#2B2224",
        "surface2": "#322629",
        "surface3": "#392B2E",
        "surface4": "#392B2E",
        "surface5": "#3F2F33",
        "surfaceVariant": "#514346",
        "tertiary": "#EEBD93",
        "tertiaryContainer": "#61401F",
        "white": "#FFFFFF"
}
},

];