export enum ActionType {
  ADD_EVENT,
  REMOVE_EVENT,
  UPDATE_EVENT,
  INCREMENT_NEXT_ID,
  SET_NEXT_ID,
  UPDATE_USER,
  UPDATE_SEMESTER,
  LOAD_EVENTS,
  SET_THEME,
  TOGGLE_THEME,
  REMOVE_SIGA,
  UPDATE_CARDAPIO,
}
